In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import warnings
warnings.filterwarnings('ignore')

In [5]:
df=pd.read_csv("C:\\Users\\Admin\\Downloads\\audi.csv")
display(df)

model  year  price transmission  mileage fuelType  tax   mpg  engineSize
0        A1  2017  12500       Manual    15735   Petrol  150  55.4         1.4
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2         2.0
2        A1  2016  11000       Manual    29946   Petrol   30  55.4         1.4
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3         2.0
4        A3  2019  17300       Manual     1998   Petrol  145  49.6         1.0
...     ...   ...    ...          ...      ...      ...  ...   ...         ...
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6         1.0
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6         1.0
10665    A3  2020  17199       Manual      609   Petrol  150  49.6         1.0
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9         1.4
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9         1.4

[10668 rows x 9 columns]

In [6]:
print (len(df))

10668


In [7]:
display (df.shape)

(10668, 9)

In [8]:
display (df.dtypes )

model            object
year              int64
price             int64
transmission     object
mileage           int64
fuelType         object
tax               int64
mpg             float64
engineSize      float64
dtype: object

In [9]:
print (df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10668 entries, 0 to 10667
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   model         10668 non-null  object 
 1   year          10668 non-null  int64  
 2   price         10668 non-null  int64  
 3   transmission  10668 non-null  object 
 4   mileage       10668 non-null  int64  
 5   fuelType      10668 non-null  object 
 6   tax           10668 non-null  int64  
 7   mpg           10668 non-null  float64
 8   engineSize    10668 non-null  float64
dtypes: float64(2), int64(4), object(3)
memory usage: 750.2+ KB
None


In [10]:
display (df.describe ())

year          price        mileage           tax           mpg  \
count  10668.000000   10668.000000   10668.000000  10668.000000  10668.000000   
mean    2017.100675   22896.685039   24827.244001    126.011436     50.770022   
std        2.167494   11714.841888   23505.257205     67.170294     12.949782   
min     1997.000000    1490.000000       1.000000      0.000000     18.900000   
25%     2016.000000   15130.750000    5968.750000    125.000000     40.900000   
50%     2017.000000   20200.000000   19000.000000    145.000000     49.600000   
75%     2019.000000   27990.000000   36464.500000    145.000000     58.900000   
max     2020.000000  145000.000000  323000.000000    580.000000    188.300000   

         engineSize  
count  10668.000000  
mean       1.930709  
std        0.602957  
min        0.000000  
25%        1.500000  
50%        2.000000  
75%        2.000000  
max        6.300000

In [11]:
X = df.iloc[:,[0,1,3,4,5,6,7,8]].values
display (X.shape)
display (X)

(10668, 8)

array([[' A1', 2017, 'Manual', ..., 150, 55.4, 1.4],
       [' A6', 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [' A1', 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [' A3', 2020, 'Manual', ..., 150, 49.6, 1.0],
       [' Q3', 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [' Q3', 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [12]:
Y = df.iloc[:,[2]].values
display (Y.shape)
display (Y)

(10668, 1)

array([[12500],
       [16500],
       [11000],
       ...,
       [17199],
       [19499],
       [15999]], dtype=int64)

In [13]:
display(pd.DataFrame(X).head(5))

0     1          2      3       4    5     6    7
0   A1  2017     Manual  15735  Petrol  150  55.4  1.4
1   A6  2016  Automatic  36203  Diesel   20  64.2  2.0
2   A1  2016     Manual  29946  Petrol   30  55.4  1.4
3   A4  2017  Automatic  25952  Diesel  145  67.3  2.0
4   A3  2019     Manual   1998  Petrol  145  49.6  1.0

In [14]:
from sklearn.preprocessing import LabelEncoder
le1 = LabelEncoder()
X[:,0] = le1.fit_transform(X[:,0])
le2 = LabelEncoder()
X[:,-4] = le2.fit_transform(X[:,-4])
display (X)


array([[0, 2017, 'Manual', ..., 150, 55.4, 1.4],
       [5, 2016, 'Automatic', ..., 20, 64.2, 2.0],
       [0, 2016, 'Manual', ..., 30, 55.4, 1.4],
       ...,
       [2, 2020, 'Manual', ..., 150, 49.6, 1.0],
       [9, 2017, 'Automatic', ..., 150, 47.9, 1.4],
       [9, 2016, 'Manual', ..., 150, 47.9, 1.4]], dtype=object)

In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers = [('encoder',OneHotEncoder(),[2])],remainder='passthrough')
X = ct.fit_transform(X)
display (X.shape)
display (pd.DataFrame(X))

(10668, 10)

0    1    2  3     4      5  6    7     8    9
0      0.0  1.0  0.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  0.0  5  2016  36203  0   20  64.2  2.0
2      0.0  1.0  0.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  0.0  3  2017  25952  0  145  67.3  2.0
4      0.0  1.0  0.0  2  2019   1998  2  145  49.6  1.0
...    ...  ...  ... ..   ...    ... ..  ...   ...  ...
10663  0.0  1.0  0.0  2  2020   4018  2  145  49.6  1.0
10664  0.0  1.0  0.0  2  2020   1978  2  150  49.6  1.0
10665  0.0  1.0  0.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  0.0  9  2017   8646  2  150  47.9  1.4
10667  0.0  1.0  0.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 10 columns]

In [16]:
display (pd.DataFrame(X))

0    1    2  3     4      5  6    7     8    9
0      0.0  1.0  0.0  0  2017  15735  2  150  55.4  1.4
1      1.0  0.0  0.0  5  2016  36203  0   20  64.2  2.0
2      0.0  1.0  0.0  0  2016  29946  2   30  55.4  1.4
3      1.0  0.0  0.0  3  2017  25952  0  145  67.3  2.0
4      0.0  1.0  0.0  2  2019   1998  2  145  49.6  1.0
...    ...  ...  ... ..   ...    ... ..  ...   ...  ...
10663  0.0  1.0  0.0  2  2020   4018  2  145  49.6  1.0
10664  0.0  1.0  0.0  2  2020   1978  2  150  49.6  1.0
10665  0.0  1.0  0.0  2  2020    609  2  150  49.6  1.0
10666  1.0  0.0  0.0  9  2017   8646  2  150  47.9  1.4
10667  0.0  1.0  0.0  9  2016  11855  2  150  47.9  1.4

[10668 rows x 10 columns]

In [17]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)
display (pd.DataFrame(X))

0         1         2         3         4         5         6  \
0     -0.583268  1.200728 -0.712333 -1.123544 -0.046450 -0.386836  1.050783   
1      1.714479 -0.832828 -0.712333 -0.160831 -0.507834  0.483989 -0.954181   
2     -0.583268  1.200728 -0.712333 -1.123544 -0.507834  0.217781  1.050783   
3      1.714479 -0.832828 -0.712333 -0.545916 -0.046450  0.047853 -0.954181   
4     -0.583268  1.200728 -0.712333 -0.738459  0.876318 -0.971285  1.050783   
...         ...       ...       ...       ...       ...       ...       ...   
10663 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.885343  1.050783   
10664 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -0.972136  1.050783   
10665 -0.583268  1.200728 -0.712333 -0.738459  1.337702 -1.030381  1.050783   
10666  1.714479 -0.832828 -0.712333  0.609339 -0.046450 -0.688442  1.050783   
10667 -0.583268  1.200728 -0.712333  0.609339 -0.507834 -0.551913  1.050783   

              7         8         9  
0      0.357147  0.357550 -0.880218  
1     -1.578323  1.037130  0.114925  
2     -1.429440  0.357550 -0.880218  
3      0.282706  1.276528  0.114925  
4      0.282706 -0.090355 -1.543647  
...         ...       ...       ...  
10663  0.282706 -0.090355 -1.543647  
10664  0.357147 -0.090355 -1.543647  
10665  0.357147 -0.090355 -1.543647  
10666  0.357147 -0.221637 -0.880218  
10667  0.357147 -0.221637 -0.880218  

[10668 rows x 10 columns]

In [18]:
from sklearn.model_selection import train_test_split
(X_train,X_test,Y_train,Y_test) = train_test_split(X,Y,test_size=0.2,random_state=0)
print (X.shape, Y.shape)
print (X_train.shape, Y_train.shape)
print (X_test.shape, Y_test.shape)

(10668, 10) (10668, 1)
(8534, 10) (8534, 1)
(2134, 10) (2134, 1)


In [19]:
from sklearn.ensemble import RandomForestRegressor
regression = RandomForestRegressor(random_state=0)
regression.fit(X_train,Y_train)
display (regression)

RandomForestRegressor(random_state=0)

In [20]:
y_pred = regression.predict(X_test)
display (y_pred)

array([14337.15, 23450.35, 27330.07, ..., 46275.18, 31359.  ,  9929.62])

In [21]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[14337.15 14998.  ]
 [23450.35 21950.  ]
 [27330.07 28990.  ]
 ...
 [46275.18 45995.  ]
 [31359.   30500.  ]
 [ 9929.62  8400.  ]]


In [22]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(Y_test, y_pred))
print  ('Mean Absolute Error', mean_absolute_error(Y_test,y_pred))

R2 Score  0.9536134841307546
Mean Absolute Error 1538.730980670462


In [23]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(X_train,Y_train)
print(reg)

LinearRegression()


In [24]:
y_pred = reg.predict(X_test)
display (y_pred)

array([[13094.92030887],
       [29381.22673171],
       [31833.88204939],
       ...,
       [42652.94253651],
       [31556.69695506],
       [ 7329.35522294]])

In [25]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),Y_test.reshape(len(Y_test),1)),1))

[[13094.92030887 14998.        ]
 [29381.22673171 21950.        ]
 [31833.88204939 28990.        ]
 ...
 [42652.94253651 45995.        ]
 [31556.69695506 30500.        ]
 [ 7329.35522294  8400.        ]]


In [26]:
from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(Y_test, y_pred))
print  ('Mean Absolute Error', mean_absolute_error(Y_test,y_pred))

R2 Score  0.79155284997024
Mean Absolute Error 3379.6412574278493


In [27]:
y_pred = reg.predict(X)
display (y_pred)

array([[14660.35891996],
       [20564.86496806],
       [13842.35891996],
       ...,
       [19436.98325652],
       [20924.66744905],
       [16719.66744905]])

In [28]:
result = pd.concat([df,pd.DataFrame(y_pred)],axis=1)
display( result)

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize             0  
0             1.4  14660.358920  
1             2.0  20564.864968  
2             1.4  13842.358920  
3             2.0  19843.084109  
4             1.0  17379.983257  
...           ...           ...  
10663         1.0  19218.983257  
10664         1.0  19305.983257  
10665         1.0  19436.983257  
10666         1.4  20924.667449  
10667         1.4  16719.667449  

[10668 rows x 10 columns]

In [29]:
from sklearn.ensemble import  ExtraTreesRegressor
ET_Model=ExtraTreesRegressor(n_estimators = 120)
ET_Model.fit(X_train,Y_train)
y_predict=ET_Model.predict(X_test)
from sklearn.metrics import r2_score,mean_absolute_error
print  ('R2 Score ', r2_score(Y_test, y_predict))
print  ('Mean Absolute Error', mean_absolute_error(Y_test,y_predict))

R2 Score  0.9568494375526752
Mean Absolute Error 1533.0819702176404


In [30]:
y_pred = reg.predict(X)
display (y_pred)
result = pd.concat([df,pd.DataFrame(y_pred)],axis=1)
display( result)

array([[14660.35891996],
       [20564.86496806],
       [13842.35891996],
       ...,
       [19436.98325652],
       [20924.66744905],
       [16719.66744905]])

model  year  price transmission  mileage fuelType  tax   mpg  \
0        A1  2017  12500       Manual    15735   Petrol  150  55.4   
1        A6  2016  16500    Automatic    36203   Diesel   20  64.2   
2        A1  2016  11000       Manual    29946   Petrol   30  55.4   
3        A4  2017  16800    Automatic    25952   Diesel  145  67.3   
4        A3  2019  17300       Manual     1998   Petrol  145  49.6   
...     ...   ...    ...          ...      ...      ...  ...   ...   
10663    A3  2020  16999       Manual     4018   Petrol  145  49.6   
10664    A3  2020  16999       Manual     1978   Petrol  150  49.6   
10665    A3  2020  17199       Manual      609   Petrol  150  49.6   
10666    Q3  2017  19499    Automatic     8646   Petrol  150  47.9   
10667    Q3  2016  15999       Manual    11855   Petrol  150  47.9   

       engineSize             0  
0             1.4  14660.358920  
1             2.0  20564.864968  
2             1.4  13842.358920  
3             2.0  19843.084109  
4             1.0  17379.983257  
...           ...           ...  
10663         1.0  19218.983257  
10664         1.0  19305.983257  
10665         1.0  19436.983257  
10666         1.4  20924.667449  
10667         1.4  16719.667449  

[10668 rows x 10 columns]

In [31]:
from sklearn.model_selection import RandomizedSearchCV
n_estimators = [int(x) for x in np.linspace(start = 80, stop = 1500, num = 10)]
max_features = ['auto', 'sqrt']
max_depth = [int(x) for x in np.linspace(6, 45, num = 5)]
min_samples_split = [2, 5, 10, 15, 100]
min_samples_leaf = [1, 2, 5, 10]

# create random grid

rand_grid={'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf}

rf=RandomForestRegressor()

rCV=RandomizedSearchCV(estimator=rf,param_distributions=rand_grid,scoring='neg_mean_squared_error',n_iter=3,cv=3,random_state=42, n_jobs = -1)

In [32]:
display (rCV.fit(X_train,Y_train))

RandomizedSearchCV(cv=3, estimator=RandomForestRegressor(), n_iter=3, n_jobs=-1,
                   param_distributions={'max_depth': [6, 15, 25, 35, 45],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 5, 10],
                                        'min_samples_split': [2, 5, 10, 15,
                                                              100],
                                        'n_estimators': [80, 237, 395, 553, 711,
                                                         868, 1026, 1184, 1342,
                                                         1500]},
                   random_state=42, scoring='neg_mean_squared_error')

In [33]:
rf_pred=rCV.predict(X_test)
display (rf_pred)

array([14041.13811241, 23753.3795236 , 28528.36978763, ...,
       48190.67701661, 31303.10628147, 10082.42651919])

In [34]:
from sklearn.metrics import mean_absolute_error,mean_squared_error
print('MAE',mean_absolute_error(Y_test,rf_pred))
print('MSE',mean_squared_error(Y_test,rf_pred))

MAE 1501.9131940843338
MSE 5693700.208337107


In [35]:
display (r2_score(Y_test,rf_pred))

0.9585659624620053

In [37]:
from catboost import CatBoostRegressor
cat=CatBoostRegressor()
print (cat.fit(X_train,Y_train))

Learning rate set to 0.057452
0:	learn: 11184.0694779	total: 145ms	remaining: 2m 24s
1:	learn: 10690.2138498	total: 149ms	remaining: 1m 14s
2:	learn: 10221.1011877	total: 154ms	remaining: 51.1s
3:	learn: 9778.8067263	total: 159ms	remaining: 39.5s
4:	learn: 9382.6454054	total: 163ms	remaining: 32.5s
5:	learn: 8989.9290587	total: 168ms	remaining: 27.8s
6:	learn: 8628.4892653	total: 173ms	remaining: 24.5s
7:	learn: 8280.9179062	total: 177ms	remaining: 22s
8:	learn: 7950.5476053	total: 182ms	remaining: 20s
9:	learn: 7636.7735365	total: 187ms	remaining: 18.5s
10:	learn: 7349.6084699	total: 191ms	remaining: 17.2s
11:	learn: 7084.0457263	total: 196ms	remaining: 16.2s
12:	learn: 6842.7060927	total: 202ms	remaining: 15.4s
13:	learn: 6608.0244743	total: 208ms	remaining: 14.7s
14:	learn: 6387.7285726	total: 215ms	remaining: 14.1s
15:	learn: 6170.1354894	total: 220ms	remaining: 13.6s
16:	learn: 5973.9133066	total: 225ms	remaining: 13s
17:	learn: 5780.4713044	total: 230ms	remaining: 12.6s
18:	learn

161:	learn: 2446.4227836	total: 998ms	remaining: 5.16s
162:	learn: 2444.2555123	total: 1.01s	remaining: 5.17s
163:	learn: 2441.5688551	total: 1.01s	remaining: 5.15s
164:	learn: 2440.2986221	total: 1.01s	remaining: 5.14s
165:	learn: 2437.3232663	total: 1.02s	remaining: 5.14s
166:	learn: 2432.4649721	total: 1.03s	remaining: 5.13s
167:	learn: 2428.3970878	total: 1.03s	remaining: 5.12s
168:	learn: 2423.6253903	total: 1.04s	remaining: 5.1s
169:	learn: 2421.4159298	total: 1.04s	remaining: 5.09s
170:	learn: 2420.5105888	total: 1.05s	remaining: 5.08s
171:	learn: 2419.1046943	total: 1.05s	remaining: 5.06s
172:	learn: 2415.9697367	total: 1.05s	remaining: 5.05s
173:	learn: 2414.6048787	total: 1.06s	remaining: 5.03s
174:	learn: 2413.5476062	total: 1.07s	remaining: 5.03s
175:	learn: 2410.0292711	total: 1.07s	remaining: 5.01s
176:	learn: 2409.2012840	total: 1.07s	remaining: 5s
177:	learn: 2404.9199084	total: 1.08s	remaining: 4.99s
178:	learn: 2403.6642991	total: 1.08s	remaining: 4.97s
179:	learn: 23

316:	learn: 2172.1935105	total: 1.78s	remaining: 3.84s
317:	learn: 2170.5700401	total: 1.79s	remaining: 3.83s
318:	learn: 2168.7470746	total: 1.79s	remaining: 3.83s
319:	learn: 2167.5437761	total: 1.8s	remaining: 3.83s
320:	learn: 2165.5790789	total: 1.81s	remaining: 3.82s
321:	learn: 2164.2609405	total: 1.81s	remaining: 3.82s
322:	learn: 2162.5119577	total: 1.82s	remaining: 3.81s
323:	learn: 2161.4811771	total: 1.82s	remaining: 3.81s
324:	learn: 2160.5458029	total: 1.83s	remaining: 3.8s
325:	learn: 2158.9245109	total: 1.83s	remaining: 3.79s
326:	learn: 2157.0096074	total: 1.84s	remaining: 3.79s
327:	learn: 2156.0953247	total: 1.85s	remaining: 3.79s
328:	learn: 2155.2997990	total: 1.85s	remaining: 3.78s
329:	learn: 2154.0676384	total: 1.86s	remaining: 3.77s
330:	learn: 2152.1472733	total: 1.86s	remaining: 3.77s
331:	learn: 2151.6773078	total: 1.87s	remaining: 3.76s
332:	learn: 2151.1380063	total: 1.88s	remaining: 3.76s
333:	learn: 2149.9980622	total: 1.88s	remaining: 3.75s
334:	learn: 

468:	learn: 2032.1024379	total: 2.58s	remaining: 2.92s
469:	learn: 2031.6525294	total: 2.58s	remaining: 2.91s
470:	learn: 2031.1200697	total: 2.59s	remaining: 2.91s
471:	learn: 2030.4309641	total: 2.6s	remaining: 2.9s
472:	learn: 2029.9703506	total: 2.6s	remaining: 2.9s
473:	learn: 2029.1619608	total: 2.61s	remaining: 2.89s
474:	learn: 2028.3173172	total: 2.61s	remaining: 2.89s
475:	learn: 2027.4450816	total: 2.62s	remaining: 2.88s
476:	learn: 2026.4852248	total: 2.62s	remaining: 2.88s
477:	learn: 2025.7125620	total: 2.63s	remaining: 2.87s
478:	learn: 2024.4385398	total: 2.63s	remaining: 2.86s
479:	learn: 2023.7573534	total: 2.64s	remaining: 2.86s
480:	learn: 2022.9267016	total: 2.64s	remaining: 2.85s
481:	learn: 2022.5285079	total: 2.65s	remaining: 2.85s
482:	learn: 2021.6201313	total: 2.65s	remaining: 2.84s
483:	learn: 2020.6956057	total: 2.66s	remaining: 2.83s
484:	learn: 2019.6415235	total: 2.66s	remaining: 2.83s
485:	learn: 2019.2660694	total: 2.67s	remaining: 2.82s
486:	learn: 20

650:	learn: 1918.5537974	total: 3.59s	remaining: 1.93s
651:	learn: 1917.9168811	total: 3.6s	remaining: 1.92s
652:	learn: 1917.4812191	total: 3.6s	remaining: 1.91s
653:	learn: 1916.8367083	total: 3.61s	remaining: 1.91s
654:	learn: 1916.2671496	total: 3.64s	remaining: 1.92s
655:	learn: 1916.0028790	total: 3.65s	remaining: 1.92s
656:	learn: 1915.4531962	total: 3.66s	remaining: 1.91s
657:	learn: 1914.7265362	total: 3.66s	remaining: 1.9s
658:	learn: 1914.2940974	total: 3.67s	remaining: 1.9s
659:	learn: 1913.9447105	total: 3.67s	remaining: 1.89s
660:	learn: 1913.2531448	total: 3.68s	remaining: 1.89s
661:	learn: 1912.5262362	total: 3.68s	remaining: 1.88s
662:	learn: 1911.8972712	total: 3.69s	remaining: 1.87s
663:	learn: 1911.3302694	total: 3.69s	remaining: 1.87s
664:	learn: 1909.9768217	total: 3.7s	remaining: 1.86s
665:	learn: 1909.3816338	total: 3.7s	remaining: 1.86s
666:	learn: 1909.1329520	total: 3.71s	remaining: 1.85s
667:	learn: 1908.7373833	total: 3.71s	remaining: 1.84s
668:	learn: 1908

835:	learn: 1832.8071890	total: 4.59s	remaining: 900ms
836:	learn: 1832.5660391	total: 4.59s	remaining: 895ms
837:	learn: 1831.9180126	total: 4.6s	remaining: 889ms
838:	learn: 1831.1675342	total: 4.61s	remaining: 884ms
839:	learn: 1830.7563210	total: 4.61s	remaining: 879ms
840:	learn: 1830.3246842	total: 4.62s	remaining: 873ms
841:	learn: 1830.0657664	total: 4.62s	remaining: 867ms
842:	learn: 1829.4229004	total: 4.63s	remaining: 862ms
843:	learn: 1828.7315034	total: 4.63s	remaining: 856ms
844:	learn: 1828.4512671	total: 4.64s	remaining: 851ms
845:	learn: 1827.8254092	total: 4.64s	remaining: 845ms
846:	learn: 1827.2232798	total: 4.65s	remaining: 839ms
847:	learn: 1826.6298672	total: 4.65s	remaining: 834ms
848:	learn: 1825.9501280	total: 4.66s	remaining: 828ms
849:	learn: 1825.7641712	total: 4.66s	remaining: 823ms
850:	learn: 1825.4470687	total: 4.67s	remaining: 817ms
851:	learn: 1825.1894602	total: 4.67s	remaining: 812ms
852:	learn: 1824.7547814	total: 4.68s	remaining: 807ms
853:	learn:

990:	learn: 1773.1775081	total: 5.4s	remaining: 49.1ms
991:	learn: 1772.8075712	total: 5.41s	remaining: 43.6ms
992:	learn: 1772.4544536	total: 5.41s	remaining: 38.2ms
993:	learn: 1772.2659066	total: 5.42s	remaining: 32.7ms
994:	learn: 1772.0462978	total: 5.42s	remaining: 27.3ms
995:	learn: 1771.2044114	total: 5.43s	remaining: 21.8ms
996:	learn: 1770.9048234	total: 5.44s	remaining: 16.4ms
997:	learn: 1770.4500877	total: 5.45s	remaining: 10.9ms
998:	learn: 1770.1346179	total: 5.46s	remaining: 5.46ms
999:	learn: 1769.8343384	total: 5.46s	remaining: 0us


In [38]:
cat_pred=cat.predict(X_test)
display (cat_pred)

array([13386.63817795, 24056.86842882, 28082.99514751, ...,
       45959.31234642, 31714.44751009,  9481.45994163])

In [39]:
display (r2_score(Y_test,cat_pred))

0.9641612028134969

In [40]:
import pickle 
# Saving model to disk
pickle.dump(cat, open('model.pkl','wb'))

In [41]:
model=pickle.load(open('model.pkl','rb'))
print (model.predict (X_train))

[14256.69390956 29475.32741129 11911.12888914 ... 21406.16876331
 17189.65426694 44839.56117235]
